Insert into municipalities(id_municipalities,name,id_city) values (Código INE,'Nombre',1);
Insert into municipalities(id_municipalities,name,id_city) values (010101,'Sucre',1);
Insert into municipalities(id_municipalities,name,id_city) values (010102,'Yotala',1);
Insert into municipalities(id_municipalities,name,id_city) values (010103,'Poroma',1);
Insert into municipalities(id_municipalities,name,id_city) values (010201,'Azurduy',1);
Insert into municipalities(id_municipalities,name,id_city) values (010202,'Tarvita',1);
Insert into municipalities(id_municipalities,name,id_city) values (010301,'Villa Zudáñez',1);
Insert into municipalities(id_municipalities,name,id_city) values (010302,'Presto',1);
Insert into municipalities(id_municipalities,name,id_city) values (010303,'Villa Mojocoya',1);
Insert into municipalities(id_municipalities,name,id_city) values (010304,'Icla',1);
Insert into municipalities(id_municipalities,name,id_city) values (010401,'Padilla',1);
Insert into municipalities(id_municipalities,name,id_city) values (010402,'Tomina',1);
Insert into municipalities(id_municipalities,name,id_city) values (010403,'Sopachuy',1);
Insert into municipalities(id_municipalities,name,id_city) values (010404,'Villa Alcalá',1);
Insert into municipalities(id_municipalities,name,id_city) values (010405,'El Villar',1);
Insert into municipalities(id_municipalities,name,id_city) values (010501,'Monteagudo',1);
Insert into municipalities(id_municipalities,name,id_city) values (010502,'Huacareta',1);
Insert into municipalities(id_municipalities,name,id_city) values (010601,'Tarabuco',1);
Insert into municipalities(id_municipalities,name,id_city) values (010602,'Yamparáez',1);
Insert into municipalities(id_municipalities,name,id_city) values (010701,'Camargo',1);
Insert into municipalities(id_municipalities,name,id_city) values (010702,'San Lucas',1);
Insert into municipalities(id_municipalities,name,id_city) values (010703,'Incahuasi',1);
Insert into municipalities(id_municipalities,name,id_city) values (010704,'Villa Charcas',1);
Insert into municipalities(id_municipalities,name,id_city) values (010801,'Villa Serrano',1);
Insert into municipalities(id_municipalities,name,id_city) values (010901,'Villa Abecia',1);
Insert into municipalities(id_municipalities,name,id_city) values (010902,'Culpina',1);
Insert into municipalities(id_municipalities,name,id_city) values (010903,'Las Carreras',1);
Insert into municipalities(id_municipalities,name,id_city) values (011001,'Villa Vaca Guzmán (Muyupampa)',1);
Insert into municipalities(id_municipalities,name,id_city) values (011002,'Huacaya',1);
Insert into municipalities(id_municipalities,name,id_city) values (011003,'Macharetí',1);
Insert into municipalities(id_municipalities,name,id_city) values (020101,'La Paz',1);
Insert into municipalities(id_municipalities,name,id_city) values (020102,'Palca',1);
Insert into municipalities(id_municipalities,name,id_city) values (020103,'Mecapaca',1);
Insert into municipalities(id_municipalities,name,id_city) values (020104,'Achocalla',1);
Insert into municipalities(id_municipalities,name,id_city) values (020105,'El Alto',1);
Insert into municipalities(id_municipalities,name,id_city) values (020201,'Achacachi',1);
Insert into municipalities(id_municipalities,name,id_city) values (020202,'Ancoraimes',1);
Insert into municipalities(id_municipalities,name,id_city) values (020203,'Chua Cocani',1);
Insert into municipalities(id_municipalities,name,id_city) values (020204,'Huarina',1);
Insert into municipalities(id_municipalities,name,id_city) values (020205,'Santiago de Huata',1);
Insert into municipalities(id_municipalities,name,id_city) values (020206,'Huatajata',1);
Insert into municipalities(id_municipalities,name,id_city) values (020301,'Coro Coro',1);
Insert into municipalities(id_municipalities,name,id_city) values (020302,'Caquiaviri',1);
Insert into municipalities(id_municipalities,name,id_city) values (020303,'Calacoto',1);
Insert into municipalities(id_municipalities,name,id_city) values (020304,'Comanche',1);
Insert into municipalities(id_municipalities,name,id_city) values (020305,'Charaña',1);
Insert into municipalities(id_municipalities,name,id_city) values (020306,'Waldo Ballivián',1);
Insert into municipalities(id_municipalities,name,id_city) values (020307,'Nazacara de Pacajes',1);
Insert into municipalities(id_municipalities,name,id_city) values (020308,'Callapa',1);
Insert into municipalities(id_municipalities,name,id_city) values (020401,'Puerto Acosta',1);
Insert into municipalities(id_municipalities,name,id_city) values (020402,'Mocomoco',1);
Insert into municipalities(id_municipalities,name,id_city) values (020403,'Puerto Carabuco',1);
Insert into municipalities(id_municipalities,name,id_city) values (020404,'Humanata',1);
Insert into municipalities(id_municipalities,name,id_city) values (020405,'Escoma',1);
Insert into municipalities(id_municipalities,name,id_city) values (020501,'Chuma',1);
Insert into municipalities(id_municipalities,name,id_city) values (020502,'Ayata',1);
Insert into municipalities(id_municipalities,name,id_city) values (020503,'Aucapata',1);
Insert into municipalities(id_municipalities,name,id_city) values (020601,'Sorata',1);
Insert into municipalities(id_municipalities,name,id_city) values (020602,'Guanay',1);
Insert into municipalities(id_municipalities,name,id_city) values (020603,'Tacacoma',1);
Insert into municipalities(id_municipalities,name,id_city) values (020604,'Quiabaya',1);
Insert into municipalities(id_municipalities,name,id_city) values (020605,'Combaya',1);
Insert into municipalities(id_municipalities,name,id_city) values (020606,'Tipuani',1);
Insert into municipalities(id_municipalities,name,id_city) values (020607,'Mapiri',1);
Insert into municipalities(id_municipalities,name,id_city) values (020608,'Teoponte',1);
Insert into municipalities(id_municipalities,name,id_city) values (020701,'Apolo',1);
Insert into municipalities(id_municipalities,name,id_city) values (020702,'Pelechuco',1);
Insert into municipalities(id_municipalities,name,id_city) values (020801,'Viacha',1);
Insert into municipalities(id_municipalities,name,id_city) values (020802,'Guaqui',1);
Insert into municipalities(id_municipalities,name,id_city) values (020803,'Tiahuanaco',1);
Insert into municipalities(id_municipalities,name,id_city) values (020804,'Desaguadero',1);
Insert into municipalities(id_municipalities,name,id_city) values (020805,'San Andrés de Machaca',1);
Insert into municipalities(id_municipalities,name,id_city) values (020806,'Jesús de Machaca',1);
Insert into municipalities(id_municipalities,name,id_city) values (020807,'Taraco',1);
Insert into municipalities(id_municipalities,name,id_city) values (020901,'Luribay',1);
Insert into municipalities(id_municipalities,name,id_city) values (020902,'Sapahaqui',1);
Insert into municipalities(id_municipalities,name,id_city) values (020903,'Yaco',1);
Insert into municipalities(id_municipalities,name,id_city) values (020904,'Malla',1);
Insert into municipalities(id_municipalities,name,id_city) values (020905,'Cairoma',1);
Insert into municipalities(id_municipalities,name,id_city) values (021001,'Inquisivi',1);
Insert into municipalities(id_municipalities,name,id_city) values (021002,'Quime',1);
Insert into municipalities(id_municipalities,name,id_city) values (021003,'Cajuata',1);
Insert into municipalities(id_municipalities,name,id_city) values (021004,'Colquiri',1);
Insert into municipalities(id_municipalities,name,id_city) values (021005,'Ichoca',1);
Insert into municipalities(id_municipalities,name,id_city) values (021006,'Licoma Pampa',1);
Insert into municipalities(id_municipalities,name,id_city) values (021101,'Chulumani',1);
Insert into municipalities(id_municipalities,name,id_city) values (021102,'Irupana',1);
Insert into municipalities(id_municipalities,name,id_city) values (021103,'Yanacachi',1);
Insert into municipalities(id_municipalities,name,id_city) values (021104,'Palos Blancos',1);
Insert into municipalities(id_municipalities,name,id_city) values (021105,'La Asunta',1);
Insert into municipalities(id_municipalities,name,id_city) values (021201,'Pucarani',1);
Insert into municipalities(id_municipalities,name,id_city) values (021202,'Laja',1);
Insert into municipalities(id_municipalities,name,id_city) values (021203,'Batallas',1);
Insert into municipalities(id_municipalities,name,id_city) values (021204,'Puerto Pérez',1);
Insert into municipalities(id_municipalities,name,id_city) values (021301,'Sica Sica',1);
Insert into municipalities(id_municipalities,name,id_city) values (021302,'Umala',1);
Insert into municipalities(id_municipalities,name,id_city) values (021303,'Ayo Ayo',1);
Insert into municipalities(id_municipalities,name,id_city) values (021304,'Calamarca',1);
Insert into municipalities(id_municipalities,name,id_city) values (021305,'Patacamaya',1);
Insert into municipalities(id_municipalities,name,id_city) values (021306,'Colquencha',1);
Insert into municipalities(id_municipalities,name,id_city) values (021307,'Collana',1);
Insert into municipalities(id_municipalities,name,id_city) values (021401,'Coroico',1);
Insert into municipalities(id_municipalities,name,id_city) values (021402,'Coripata',1);
Insert into municipalities(id_municipalities,name,id_city) values (021501,'Ixiamas',1);
Insert into municipalities(id_municipalities,name,id_city) values (021502,'San Buenaventura',1);
Insert into municipalities(id_municipalities,name,id_city) values (021601,'Charazani',1);
Insert into municipalities(id_municipalities,name,id_city) values (021602,'Curva',1);
Insert into municipalities(id_municipalities,name,id_city) values (021701,'Copacabana',1);
Insert into municipalities(id_municipalities,name,id_city) values (021702,'San Pedro de Tiquina',1);
Insert into municipalities(id_municipalities,name,id_city) values (021703,'Tito Yupanqui',1);
Insert into municipalities(id_municipalities,name,id_city) values (021801,'San Pedro de Curahuara',1);
Insert into municipalities(id_municipalities,name,id_city) values (021802,'Papel Pampa',1);
Insert into municipalities(id_municipalities,name,id_city) values (021803,'Chacarilla',1);
Insert into municipalities(id_municipalities,name,id_city) values (021901,'Santiago de Machaca',1);
Insert into municipalities(id_municipalities,name,id_city) values (021902,'Catacora',1);
Insert into municipalities(id_municipalities,name,id_city) values (022001,'Caranavi',1);
Insert into municipalities(id_municipalities,name,id_city) values (022002,'Alto Beni',1);
Insert into municipalities(id_municipalities,name,id_city) values (030101,'Cochabamba',1);
Insert into municipalities(id_municipalities,name,id_city) values (030201,'Aiquile',1);
Insert into municipalities(id_municipalities,name,id_city) values (030202,'Pasorapa',1);
Insert into municipalities(id_municipalities,name,id_city) values (030203,'Omereque',1);
Insert into municipalities(id_municipalities,name,id_city) values (030301,'Independencia',1);
Insert into municipalities(id_municipalities,name,id_city) values (030302,'Morochata',1);
Insert into municipalities(id_municipalities,name,id_city) values (030303,'Cocapata',1);
Insert into municipalities(id_municipalities,name,id_city) values (030401,'Tarata',1);
Insert into municipalities(id_municipalities,name,id_city) values (030402,'Anzaldo',1);
Insert into municipalities(id_municipalities,name,id_city) values (030403,'Arbieto',1);
Insert into municipalities(id_municipalities,name,id_city) values (030404,'Sacabamba',1);
Insert into municipalities(id_municipalities,name,id_city) values (030501,'Arani',1);
Insert into municipalities(id_municipalities,name,id_city) values (030502,'Vacas',1);
Insert into municipalities(id_municipalities,name,id_city) values (030601,'Arque',1);
Insert into municipalities(id_municipalities,name,id_city) values (030602,'Tacopaya',1);
Insert into municipalities(id_municipalities,name,id_city) values (030701,'Capinota',1);
Insert into municipalities(id_municipalities,name,id_city) values (030702,'Santiváñez',1);
Insert into municipalities(id_municipalities,name,id_city) values (030703,'Sicaya',1);
Insert into municipalities(id_municipalities,name,id_city) values (030801,'Cliza',1);
Insert into municipalities(id_municipalities,name,id_city) values (030802,'Toco',1);
Insert into municipalities(id_municipalities,name,id_city) values (030803,'Tolata',1);
Insert into municipalities(id_municipalities,name,id_city) values (030901,'Quillacollo',1);
Insert into municipalities(id_municipalities,name,id_city) values (030902,'Sipe Sipe',1);
Insert into municipalities(id_municipalities,name,id_city) values (030903,'Tiquipaya',1);
Insert into municipalities(id_municipalities,name,id_city) values (030904,'Vinto',1);
Insert into municipalities(id_municipalities,name,id_city) values (030905,'Colcapirhua',1);
Insert into municipalities(id_municipalities,name,id_city) values (031001,'Sacaba',1);
Insert into municipalities(id_municipalities,name,id_city) values (031002,'Colomi',1);
Insert into municipalities(id_municipalities,name,id_city) values (031003,'Villa Tunari',1);
Insert into municipalities(id_municipalities,name,id_city) values (031101,'Tapacarí',1);
Insert into municipalities(id_municipalities,name,id_city) values (031201,'Totora',1);
Insert into municipalities(id_municipalities,name,id_city) values (031202,'Pojo',1);
Insert into municipalities(id_municipalities,name,id_city) values (031203,'Pocona',1);
Insert into municipalities(id_municipalities,name,id_city) values (031204,'Chimoré',1);
Insert into municipalities(id_municipalities,name,id_city) values (031205,'Puerto Villarroel',1);
Insert into municipalities(id_municipalities,name,id_city) values (031206,'Entre Ríos',1);
Insert into municipalities(id_municipalities,name,id_city) values (031301,'Mizque',1);
Insert into municipalities(id_municipalities,name,id_city) values (031302,'Vila Vila',1);
Insert into municipalities(id_municipalities,name,id_city) values (031303,'Alalay',1);
Insert into municipalities(id_municipalities,name,id_city) values (031401,'Punata',1);
Insert into municipalities(id_municipalities,name,id_city) values (031402,'Villa Rivero',1);
Insert into municipalities(id_municipalities,name,id_city) values (031403,'San Benito',1);
Insert into municipalities(id_municipalities,name,id_city) values (031404,'Tacachi',1);
Insert into municipalities(id_municipalities,name,id_city) values (031405,'Cuchumuela',1);
Insert into municipalities(id_municipalities,name,id_city) values (031501,'Bolívar',1);
Insert into municipalities(id_municipalities,name,id_city) values (031601,'Tiraque',1);
Insert into municipalities(id_municipalities,name,id_city) values (031602,'Shinahota',1);
Insert into municipalities(id_municipalities,name,id_city) values (040101,'Oruro',1);
Insert into municipalities(id_municipalities,name,id_city) values (040102,'Caracollo',1);
Insert into municipalities(id_municipalities,name,id_city) values (040103,'El Choro',1);
Insert into municipalities(id_municipalities,name,id_city) values (040104,'Paria',1);
Insert into municipalities(id_municipalities,name,id_city) values (040201,'Challapata',1);
Insert into municipalities(id_municipalities,name,id_city) values (040202,'Quillacas',1);
Insert into municipalities(id_municipalities,name,id_city) values (040301,'Corque',1);
Insert into municipalities(id_municipalities,name,id_city) values (040302,'Choquecota',1);
Insert into municipalities(id_municipalities,name,id_city) values (040401,'Curahuara de Carangas',1);
Insert into municipalities(id_municipalities,name,id_city) values (040402,'Turco',1);
Insert into municipalities(id_municipalities,name,id_city) values (040501,'Huachacalla',1);
Insert into municipalities(id_municipalities,name,id_city) values (040502,'Escara',1);
Insert into municipalities(id_municipalities,name,id_city) values (040503,'Cruz de Machacamarca',1);
Insert into municipalities(id_municipalities,name,id_city) values (040504,'Yunguyo de Litoral',1);
Insert into municipalities(id_municipalities,name,id_city) values (040505,'Esmeralda',1);
Insert into municipalities(id_municipalities,name,id_city) values (040601,'Poopó',1);
Insert into municipalities(id_municipalities,name,id_city) values (040602,'Pazña',1);
Insert into municipalities(id_municipalities,name,id_city) values (040603,'Antequera',1);
Insert into municipalities(id_municipalities,name,id_city) values (040701,'Huanuni',1);
Insert into municipalities(id_municipalities,name,id_city) values (040702,'Machacamarca',1);
Insert into municipalities(id_municipalities,name,id_city) values (040801,'Salinas de Garci Mendoza',1);
Insert into municipalities(id_municipalities,name,id_city) values (040802,'Pampa Aullagas',1);
Insert into municipalities(id_municipalities,name,id_city) values (040901,'Sabaya',1);
Insert into municipalities(id_municipalities,name,id_city) values (040902,'Coipasa',1);
Insert into municipalities(id_municipalities,name,id_city) values (040903,'Chipaya',1);
Insert into municipalities(id_municipalities,name,id_city) values (041001,'Toledo',1);
Insert into municipalities(id_municipalities,name,id_city) values (041101,'Eucaliptus',1);
Insert into municipalities(id_municipalities,name,id_city) values (041201,'Santiago de Andamarca',1);
Insert into municipalities(id_municipalities,name,id_city) values (041202,'Belén de Andamarca',1);
Insert into municipalities(id_municipalities,name,id_city) values (041301,'Totora',1);
Insert into municipalities(id_municipalities,name,id_city) values (041401,'Santiago de Huari',1);
Insert into municipalities(id_municipalities,name,id_city) values (041501,'La Rivera',1);
Insert into municipalities(id_municipalities,name,id_city) values (041502,'Todos Santos',1);
Insert into municipalities(id_municipalities,name,id_city) values (041503,'Carangas',1);
Insert into municipalities(id_municipalities,name,id_city) values (041601,'Huayllamarca',1);
Insert into municipalities(id_municipalities,name,id_city) values (050101,'Potosí',1);
Insert into municipalities(id_municipalities,name,id_city) values (050102,'Tinguipaya',1);
Insert into municipalities(id_municipalities,name,id_city) values (050103,'Yocalla',1);
Insert into municipalities(id_municipalities,name,id_city) values (050104,'Urmiri',1);
Insert into municipalities(id_municipalities,name,id_city) values (050201,'Uncía',1);
Insert into municipalities(id_municipalities,name,id_city) values (050202,'Chayanta',1);
Insert into municipalities(id_municipalities,name,id_city) values (050203,'Llallagua',1);
Insert into municipalities(id_municipalities,name,id_city) values (050204,'Chuquihuta',1);
Insert into municipalities(id_municipalities,name,id_city) values (050301,'Betanzos',1);
Insert into municipalities(id_municipalities,name,id_city) values (050302,'Chaquí',1);
Insert into municipalities(id_municipalities,name,id_city) values (050303,'Tacobamba',1);
Insert into municipalities(id_municipalities,name,id_city) values (050401,'Colquechaca',1);
Insert into municipalities(id_municipalities,name,id_city) values (050402,'Ravelo',1);
Insert into municipalities(id_municipalities,name,id_city) values (050403,'Pocoata',1);
Insert into municipalities(id_municipalities,name,id_city) values (050404,'Ocurí',1);
Insert into municipalities(id_municipalities,name,id_city) values (050405,'San Pedro de Macha',1);
Insert into municipalities(id_municipalities,name,id_city) values (050501,'San Pedro de Buena Vista',1);
Insert into municipalities(id_municipalities,name,id_city) values (050502,'Toro Toro',1);
Insert into municipalities(id_municipalities,name,id_city) values (050601,'Cotagaita',1);
Insert into municipalities(id_municipalities,name,id_city) values (050602,'Vitichi',1);
Insert into municipalities(id_municipalities,name,id_city) values (050701,'Sacaca',1);
Insert into municipalities(id_municipalities,name,id_city) values (050702,'Caripuyo',1);
Insert into municipalities(id_municipalities,name,id_city) values (050801,'Tupiza',1);
Insert into municipalities(id_municipalities,name,id_city) values (050802,'Atocha',1);
Insert into municipalities(id_municipalities,name,id_city) values (050901,'Colcha K',1);
Insert into municipalities(id_municipalities,name,id_city) values (050902,'San Pedro de Quemes',1);
Insert into municipalities(id_municipalities,name,id_city) values (051001,'San Pablo de Lípez',1);
Insert into municipalities(id_municipalities,name,id_city) values (051002,'Mojinete',1);
Insert into municipalities(id_municipalities,name,id_city) values (051003,'San Antonio de Esmoruco',1);
Insert into municipalities(id_municipalities,name,id_city) values (051101,'Puna',1);
Insert into municipalities(id_municipalities,name,id_city) values (051102,'Caiza D',1);
Insert into municipalities(id_municipalities,name,id_city) values (051103,'Ckochas',1);
Insert into municipalities(id_municipalities,name,id_city) values (051201,'Uyuni',1);
Insert into municipalities(id_municipalities,name,id_city) values (051202,'Tomave',1);
Insert into municipalities(id_municipalities,name,id_city) values (051203,'Porco',1);
Insert into municipalities(id_municipalities,name,id_city) values (051301,'Arampampa',1);
Insert into municipalities(id_municipalities,name,id_city) values (051302,'Acasio',1);
Insert into municipalities(id_municipalities,name,id_city) values (051401,'Llica',1);
Insert into municipalities(id_municipalities,name,id_city) values (051402,'Tahua',1);
Insert into municipalities(id_municipalities,name,id_city) values (051501,'Villazón',1);
Insert into municipalities(id_municipalities,name,id_city) values (051601,'San Agustín',1);
Insert into municipalities(id_municipalities,name,id_city) values (060101,'Tarija',1);
Insert into municipalities(id_municipalities,name,id_city) values (060201,'Padcaya',1);
Insert into municipalities(id_municipalities,name,id_city) values (060202,'Bermejo',1);
Insert into municipalities(id_municipalities,name,id_city) values (060301,'Yacuiba',1);
Insert into municipalities(id_municipalities,name,id_city) values (060302,'Caraparí',1);
Insert into municipalities(id_municipalities,name,id_city) values (060303,'Villa Montes',1);
Insert into municipalities(id_municipalities,name,id_city) values (060401,'Uriondo',1);
Insert into municipalities(id_municipalities,name,id_city) values (060402,'Yunchará',1);
Insert into municipalities(id_municipalities,name,id_city) values (060501,'San Lorenzo',1);
Insert into municipalities(id_municipalities,name,id_city) values (060502,'El Puente',1);
Insert into municipalities(id_municipalities,name,id_city) values (060601,'Entre Ríos',1);
Insert into municipalities(id_municipalities,name,id_city) values (070101,'Santa Cruz de la Sierra',1);
Insert into municipalities(id_municipalities,name,id_city) values (070102,'Cotoca',1);
Insert into municipalities(id_municipalities,name,id_city) values (070103,'Porongo',1);
Insert into municipalities(id_municipalities,name,id_city) values (070104,'La Guardia',1);
Insert into municipalities(id_municipalities,name,id_city) values (070105,'El Torno',1);
Insert into municipalities(id_municipalities,name,id_city) values (070201,'Warnes',1);
Insert into municipalities(id_municipalities,name,id_city) values (070202,'Okinawa Uno',1);
Insert into municipalities(id_municipalities,name,id_city) values (070301,'San Ignacio de Velasco',1);
Insert into municipalities(id_municipalities,name,id_city) values (070302,'San Miguel de Velasco',1);
Insert into municipalities(id_municipalities,name,id_city) values (070303,'San Rafael de Velasco',1);
Insert into municipalities(id_municipalities,name,id_city) values (070401,'Buena Vista',1);
Insert into municipalities(id_municipalities,name,id_city) values (070402,'San Carlos',1);
Insert into municipalities(id_municipalities,name,id_city) values (070403,'Villa Yapacaní',1);
Insert into municipalities(id_municipalities,name,id_city) values (070404,'San Juan de Yapacaní',1);
Insert into municipalities(id_municipalities,name,id_city) values (070501,'San José de Chiquitos',1);
Insert into municipalities(id_municipalities,name,id_city) values (070502,'Pailón',1);
Insert into municipalities(id_municipalities,name,id_city) values (070503,'Roboré',1);
Insert into municipalities(id_municipalities,name,id_city) values (070601,'Portachuelo',1);
Insert into municipalities(id_municipalities,name,id_city) values (070602,'Santa Rosa del Sara',1);
Insert into municipalities(id_municipalities,name,id_city) values (070603,'Colpa Bélgica',1);
Insert into municipalities(id_municipalities,name,id_city) values (070701,'Lagunillas',1);
Insert into municipalities(id_municipalities,name,id_city) values (070702,'Charagua',1);
Insert into municipalities(id_municipalities,name,id_city) values (070703,'Cabezas',1);
Insert into municipalities(id_municipalities,name,id_city) values (070704,'Cuevo',1);
Insert into municipalities(id_municipalities,name,id_city) values (070705,'Gutiérrez',1);
Insert into municipalities(id_municipalities,name,id_city) values (070706,'Camiri',1);
Insert into municipalities(id_municipalities,name,id_city) values (070707,'Boyuibe',1);
Insert into municipalities(id_municipalities,name,id_city) values (070801,'Vallegrande',1);
Insert into municipalities(id_municipalities,name,id_city) values (070802,'El Trigal',1);
Insert into municipalities(id_municipalities,name,id_city) values (070803,'Moro Moro',1);
Insert into municipalities(id_municipalities,name,id_city) values (070804,'Postrervalle',1);
Insert into municipalities(id_municipalities,name,id_city) values (070805,'Pucará',1);
Insert into municipalities(id_municipalities,name,id_city) values (070901,'Samaipata',1);
Insert into municipalities(id_municipalities,name,id_city) values (070902,'Pampagrande',1);
Insert into municipalities(id_municipalities,name,id_city) values (070903,'Mairana',1);
Insert into municipalities(id_municipalities,name,id_city) values (070904,'Quirusillas',1);
Insert into municipalities(id_municipalities,name,id_city) values (071001,'Montero',1);
Insert into municipalities(id_municipalities,name,id_city) values (071002,'General Saavedra',1);
Insert into municipalities(id_municipalities,name,id_city) values (071003,'Mineros',1);
Insert into municipalities(id_municipalities,name,id_city) values (071004,'Fernández Alonso',1);
Insert into municipalities(id_municipalities,name,id_city) values (071005,'San Pedro',1);
Insert into municipalities(id_municipalities,name,id_city) values (071101,'Concepción',1);
Insert into municipalities(id_municipalities,name,id_city) values (071102,'San Javier',1);
Insert into municipalities(id_municipalities,name,id_city) values (071103,'San Julián',1);
Insert into municipalities(id_municipalities,name,id_city) values (071104,'San Ramón',1);
Insert into municipalities(id_municipalities,name,id_city) values (071105,'San Antonio de Lomerío',1);
Insert into municipalities(id_municipalities,name,id_city) values (071106,'Cuatro Cañadas',1);
Insert into municipalities(id_municipalities,name,id_city) values (071201,'San Matías',1);
Insert into municipalities(id_municipalities,name,id_city) values (071301,'Comarapa',1);
Insert into municipalities(id_municipalities,name,id_city) values (071302,'Saipina',1);
Insert into municipalities(id_municipalities,name,id_city) values (071401,'Puerto Suárez',1);
Insert into municipalities(id_municipalities,name,id_city) values (071402,'Puerto Quijarro',1);
Insert into municipalities(id_municipalities,name,id_city) values (071403,'El Carmen Rivero Tórrez',1);
Insert into municipalities(id_municipalities,name,id_city) values (071501,'Ascensión de Guarayos',1);
Insert into municipalities(id_municipalities,name,id_city) values (071502,'Urubichá',1);
Insert into municipalities(id_municipalities,name,id_city) values (071503,'El Puente',1);
Insert into municipalities(id_municipalities,name,id_city) values (080101,'Trinidad',1);
Insert into municipalities(id_municipalities,name,id_city) values (080102,'San Javier',1);
Insert into municipalities(id_municipalities,name,id_city) values (080201,'Riberalta',1);
Insert into municipalities(id_municipalities,name,id_city) values (080202,'Guayaramerín',1);
Insert into municipalities(id_municipalities,name,id_city) values (080301,'Reyes',1);
Insert into municipalities(id_municipalities,name,id_city) values (080302,'San Borja',1);
Insert into municipalities(id_municipalities,name,id_city) values (080303,'Santa Rosa',1);
Insert into municipalities(id_municipalities,name,id_city) values (080304,'Rurrenabaque',1);
Insert into municipalities(id_municipalities,name,id_city) values (080401,'Santa Ana del Yacuma',1);
Insert into municipalities(id_municipalities,name,id_city) values (080402,'Exaltación',1);
Insert into municipalities(id_municipalities,name,id_city) values (080501,'San Ignacio de Moxos',1);
Insert into municipalities(id_municipalities,name,id_city) values (080601,'Loreto',1);
Insert into municipalities(id_municipalities,name,id_city) values (080602,'San Andrés',1);
Insert into municipalities(id_municipalities,name,id_city) values (080701,'San Joaquín',1);
Insert into municipalities(id_municipalities,name,id_city) values (080702,'San Ramón',1);
Insert into municipalities(id_municipalities,name,id_city) values (080703,'Puerto Siles',1);
Insert into municipalities(id_municipalities,name,id_city) values (080801,'Magdalena',1);
Insert into municipalities(id_municipalities,name,id_city) values (080802,'Baures',1);
Insert into municipalities(id_municipalities,name,id_city) values (080803,'Huacaraje',1);
Insert into municipalities(id_municipalities,name,id_city) values (090101,'Cobija',1);
Insert into municipalities(id_municipalities,name,id_city) values (090102,'Porvenir',1);
Insert into municipalities(id_municipalities,name,id_city) values (090103,'Bolpebra',1);
Insert into municipalities(id_municipalities,name,id_city) values (090104,'Bella Flor',1);
Insert into municipalities(id_municipalities,name,id_city) values (090201,'Puerto Rico',1);
Insert into municipalities(id_municipalities,name,id_city) values (090202,'San Pedro',1);
Insert into municipalities(id_municipalities,name,id_city) values (090203,'Filadelfia',1);
Insert into municipalities(id_municipalities,name,id_city) values (090301,'Puerto Gonzalo Moreno',1);
Insert into municipalities(id_municipalities,name,id_city) values (090302,'San Lorenzo',1);
Insert into municipalities(id_municipalities,name,id_city) values (090303,'Sena',1);
Insert into municipalities(id_municipalities,name,id_city) values (090401,'Santa Rosa del Abuná',1);
Insert into municipalities(id_municipalities,name,id_city) values (090402,'Ingavi',1);
Insert into municipalities(id_municipalities,name,id_city) values (090501,'Nueva Esperanza',1);
Insert into municipalities(id_municipalities,name,id_city) values (090502,'Villa Nueva',1);
Insert into municipalities(id_municipalities,name,id_city) values (090503,'Santos Mercado',1);
